### ISSUE TITLE
Redisgn wrist module

### ISSUE THREAD

**Issue by bcfay** [Partial-Hand-Prosthesis-Experimental/MQP-monorepo#15]
- unified pcb layout, blocking 
- new batteries
- new servo
- old servo
- Display
- buttons on protoboard

**Comment by bcfay** [comment]
routing for vibrohaptic motors

**Comment by lcreid1** [comment]
Image with a general layout
![WristMod](https://user-images.githubusercontent.com/42653066/163693298-102438a3-bc0a-4379-b6f7-48ef4cda1699.PNG)

**Comment by lcreid1** [comment]
2 6 pin JST

- 1 for 6 hall effects
- 1 for 5 velo and 1 3.3v for velo

6 2 pin JST

- 1 for vin and gnd for hall effect
- rest for haptic motors

would be nice not necessary

**Comment by bcfay** [comment]
@lcreid1 can i get the hight for the pcb

**Comment by lcreid1** [comment]
@bcfay 5mm

**Comment by bcfay** [comment]
less than sevo body for sevo controll parts

**Comment by Drewsapple** [comment]
Okay servo controller is actually 26x24x14mm, tiny bit bigger than the servo on depth
