### ISSUE TITLE
Wrist display and power button

### ISSUE THREAD

**Issue by lcreid1** [Partial-Hand-Prosthesis-Experimental/MQP-monorepo#24]
Allow user to switch some settings from the wrist module, not as extensive as the Web App
Calibration procedure

**Comment by lcreid1** [comment]
stretch goal

**Comment by lcreid1** [comment]
Select buttons and display

**Comment by lcreid1** [comment]
https://www.amazon.com/HiLetgo-Serial-128X64-Display-Color/dp/B06XRBTBTB/ref=sr_1_4?crid=A5EF7W2QSPOG&keywords=LCD%2BDisplay%2B4%2BPin&qid=1649178478&sprefix=lcd%2Bdisplay%2B4%2Bpin%2Caps%2C147&sr=8-4&th=1

**Comment by bcfay** [comment]
- able to select vibrohaptic profile
- select thumb control profile
-

**Comment by lcreid1** [comment]
no longer needed trival
