### ISSUE TITLE
Finish list of PCB requirements

### ISSUE THREAD

**Issue by Drewsapple** [Partial-Hand-Prosthesis-Experimental/MQP-monorepo#3]

**Comment by lcreid1** [comment]
Partnered with separate issues
Vibrohaptic drivers
ADCs and Inamps for touch sense
ADC for motor current (?)
Battery regulator [[stretch]] 2S to 5V
esp32pico
Amplifiers for velostat
pins to connect i2c display
pinouts for the hall effect sensor PCB
pinouts for both servos

**Comment by lcreid1** [comment]
Possibly multiplexing

**Comment by lcreid1** [comment]
Hall effect inAmps

**Comment by lcreid1** [comment]
lipo charging circuit
