### ISSUE TITLE
Index Finger 

### ISSUE THREAD

**Issue by lcreid1** [Partial-Hand-Prosthesis-Experimental/MQP-monorepo#57]
Specifically depth

**Comment by bcfay** [comment]
Increase Tolerance on Spring Steel Slots

**Comment by bcfay** [comment]
beef up slots supports

**Comment by lcreid1** [comment]
less of a lip on the middle velostat spot or raised in general

**Comment by bcfay** [comment]
bottom piece boudin cable should be press fit
reprint flexing element in other material tpu
make medicarpal falange tpu cap deeper
add grove for cable in mp joint
smooth out bottom part of index finger
guides for wires

**Comment by bcfay** [comment]
make L shaped hole for cable to tie off in and get jammed into after being pulled
